### ISSUE TITLE
Incorrect links to chapters by too many #

### ISSUE THREAD

**Issue by gcarreno** [zoltanleo/fpc_lazarus_notes#3]
Hey ZoltanLeo(@zoltanleo),

I was looking at the source of the MD files and found out that you're using too many `#`.

It only needs one.

You can attest that by clicking on the menu to the left of the `README.md` title above all the text.
An image better than a thousand words, right:
![Selection_002](https://user-images.githubusercontent.com/81799/133941792-b94e2856-5526-40c6-adbe-1752dcc04b5b.png)
This menu is quite recent.

Cheers,
Gus

**Comment by zoltanleo** [comment]
Hi Gus (@ gcarreno)

I don't quite understand what you mean when you talk about "extra" #. According to the MD file specification, the header level is determined by the number of '#' characters.

https://guides.github.com/features/mastering-markdown/#examples

When converting to other formats, this allows you to correctly form the table of contents of the text.

Or did you mean something else?

**Comment by gcarreno** [comment]
Hey Zoltan(@zoltanleo),

> Or did you mean something else?

Sorry for the confusion, mea culpa, and yes I mean something else.

I'm not talking of when you declare a header, that you  are doing correctly:
```markdowon
### Header Level Three
```

I'm talking about when you link to that header, that you are doing incorrectly:
```markdown
[Header Level Three](#header-level-three) <!-- Correct way -->
[Header Level Three](###header-level-three) <!-- Incorrect way -->
```

The part inside the curved brackets is a `URL` and in a `URL` the `#` part has only one `#`, right?
You're putting as many `#` has are in the Markdown header, which is incorrect.

Hope this clarifies the issue :smile: 

Cheers,
Gus

**Comment by zoltanleo** [comment]
> The part inside the curved brackets is a `URL` and in a `URL` the `#` part has only one `#`, right?
> You're putting as many `#` has are in the Markdown header, which is incorrect.

Hi Gus (@gcarreno)

You're right. It's enough to specify one '#' sign.
Thanks for the valuable comment. I'm fixed it. :)

**Comment by gcarreno** [comment]
Hey Zoltan(@zoltanleo),

> Thanks for the valuable comment.

You are more than welcome!!

> I'm fixed it. :)

That's awesome sauce!!

I've looked at the commit and I'm closing this issue cuz it's now solved.

As usual, many thanks for the quick response!!

Cheers,
Gus
